# -*- coding: utf-8 -*-
"""Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CtAhYzFF3fuWeoARgQs5gJZsFe597cuO

# Upload drive
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from scipy.interpolate import griddata
import plotly.graph_objects as go

"""# Add Generic functions"""

def read_dataset(filename, path, date_col=None):

    full_path = f'{path}/{filename}'

    try:
        if filename.lower().endswith('.csv'):
            if date_col:
                df = pd.read_csv(full_path, parse_dates=[date_col])
            else:
                df = pd.read_csv(full_path)

        elif filename.lower().endswith(('.xlsx', '.xls')):
            if date_col:
                df = pd.read_excel(full_path, parse_dates=[date_col])
            else:
                df = pd.read_excel(full_path)

        else:
            raise ValueError("Unsupported file format. Only .csv, .xlsx, and .xls are supported.")

        # Drop unnecessary index columns
        df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
        print(df.dtypes)

        return df

    except FileNotFoundError:
        raise FileNotFoundError(f"The file '{full_path}' was not found.")

"""# Add path"""

path_to_drive = 'drive/MyDrive/Optimization'

"""#Input Analysis

## Consumption Analysis
"""

# Load Excel file
df_consumption_2018 = read_dataset('consumption_se_2018.xlsx',path_to_drive)
# Prepare timeseries
df_consumption_2018['datetime'] = pd.date_range(start='2018-01-01 00:00', periods=len(df_consumption_2018), freq='h')
df_consumption_2018.set_index('datetime', inplace=True)

# Convert MW to GWh (1 MW for 1 hour = 0.001 GWh)
df_gwh = df_consumption_2018 * 0.001

# Combined Graph
plt.figure(figsize=(16, 6))
for col in df_gwh.columns:
    plt.plot(df_gwh.index, df_gwh[col], label=col.upper())  # transparency for overlap
#plt.title('Hourly Power Consumption in Sweden by Bidding Zone (2018)')
plt.xlabel('Date')
plt.ylabel('Consumption (GWh)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


#alternate showing with blue shades:

# Define smooth blue color palette (4 bidding zones)
colors = plt.cm.Blues(np.linspace(0.3, 0.95, len(df_gwh.columns)))
# 0.3–0.85 avoids very light and very dark extremes

# Combined Graph
plt.figure(figsize=(14, 6))

for col, color in zip(df_gwh.columns, colors):
    plt.plot(
        df_gwh.index,
        df_gwh[col],
        label=col.upper(),
        color=color,
        linewidth=2.0
    )

plt.xlabel('Date', fontsize=20)
plt.ylabel('Consumption (GWh)', fontsize=20)

# Larger legend
plt.legend(
    fontsize=14,          # bigger text
    title="Bidding Zones",
    title_fontsize=14,
    loc="upper right",
    frameon=True
)

plt.grid(True, alpha=0.5)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.tight_layout()
plt.show()

# Individual Zone Plots
for zone in df_gwh.columns:
    plt.figure(figsize=(15, 4))
    plt.plot(df_gwh.index, df_gwh[zone], label=zone.upper(), color='tab:blue')
    plt.title(f'Hourly Power Consumption in Zone {zone.upper()} (2018)')
    plt.xlabel('Date')
    plt.ylabel('Consumption (GWh)')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

"""## Availability Factor by VRE Technology"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your Excel file
df_vre_2018 = read_dataset('vre_se_2018.xlsx',path_to_drive)

# Convert time (like t1, t2...) into numeric time index
df_vre_2018['time'] = df_vre_2018.groupby('technology').cumcount() + 1

# Keep relevant columns
vre_clean = df_vre_2018[['time', 'technology', 'se1', 'se2', 'se3', 'se4']]

# Melt to long format: each row is one time-technology-zone observation
vre_long = vre_clean.melt(id_vars=['time', 'technology'],
                          value_vars=['se1', 'se2', 'se3', 'se4'],
                          var_name='zone', value_name='availability')

# Define colors for clarity
#colors = {
#    'wind': '#66c2a5',   # light green
#    'solar': '#fdc086'   # light orange
#}

colors = {
    'wind':  '#238b45',  # medium-light blue (darker than before)
    'solar': '#08519c'   # deep blue
}
# Plot one figure per zone
sns.set(style="whitegrid")
zones = ['se1', 'se2', 'se3', 'se4']

for zone in zones:
    plt.figure(figsize=(14, 6))

    for tech in ['wind', 'solar']:
        subset = vre_long[(vre_long['zone'] == zone) & (vre_long['technology'] == tech)]
        plt.plot(subset['time'], subset['availability'],
                 label=tech.title(),
                 color=colors[tech],
                 linewidth=1)

    #plt.title(f'Availability Factor for VRE in {zone.upper()} (2018)')
    plt.xlabel('Hour of Year', fontsize=20)
    plt.ylabel('Availability Factor', fontsize=20)
    plt.legend(
      title="Technology",
      fontsize=16,
      title_fontsize=16,
      frameon=True
    )
    plt.grid(True, alpha=0.3)
    plt.xticks(fontsize=18)
    plt.yticks(fontsize=18)
    plt.tight_layout()
    plt.show()

"""## Daily Inflow by Bidding Zone"""

# Load Excel file
daily_inflow_2018 = read_dataset('inflow_res_se_2018.xlsx',path_to_drive)

# Extract relevant data
daily_inflow = daily_inflow_2018[['Daily inflow (GWh)', 'se1', 'se2', 'se3', 'se4']].copy()
daily_inflow.rename(columns={'Daily inflow (GWh)': 'day'}, inplace=True)
# Prepare timeseries
daily_inflow['day_index'] = range(1, len(daily_inflow) + 1)

# Optional: Normalize inflows per zone (comment out to use raw GWh)
normalize = False
if normalize:
    for zone in ['se1', 'se2', 'se3', 'se4']:
        max_val = daily_inflow[zone].max()
        if max_val != 0:
            daily_inflow[zone] = daily_inflow[zone] / max_val

# Compute total inflow and rolling averages ===
daily_inflow['total'] = daily_inflow[['se1', 'se2', 'se3', 'se4']].sum(axis=1)

for zone in ['se1', 'se2', 'se3', 'se4', 'total']:
    daily_inflow[f'{zone}_roll7'] = daily_inflow[zone].rolling(window=7, center=True).mean()

# Plot smoothed inflows
colors = {'se1': 'tab:red', 'se2': 'tab:green', 'se3': 'tab:purple', 'se4': 'tab:orange', 'total': 'tab:blue'}

plt.figure(figsize=(14, 6))
for zone in ['se1', 'se2', 'se3', 'se4']:
    plt.plot(daily_inflow['day_index'], daily_inflow[zone],
             label=zone.upper(), linewidth=2)

plt.title('Daily Inflow by Bidding Zone (2018) – Raw Data', fontsize=16)
plt.xlabel('Day of Year', fontsize=20)
plt.ylabel('Inflow (GWh)' if not normalize else 'Normalized Inflow', fontsize=20)
plt.legend(fontsize=18)
plt.grid(True)
plt.tick_params(axis='both', which='major', labelsize=16)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.tight_layout()
plt.show()

plt.savefig('daily_inflow_smoothed.png', dpi=300)

"""## Net Import by bidding Zone"""

# Load Excel file
df_netimport_2018 = read_dataset('netimport_se_2018.xlsx',path_to_drive)

# Extract relevant data
hourly_net_import = df_netimport_2018[['hour', 'se1', 'se2', 'se3', 'se4']].copy()
hourly_net_import['hour_index'] = range(1, len(hourly_net_import) + 1)

#  Compute Daily Average
# Group every 24 hours to compute daily average
daily_avg_inflow = hourly_net_import[['se1', 'se2', 'se3', 'se4']].groupby(hourly_net_import.index // 24).mean()
daily_avg_inflow['day_index'] = range(1, len(daily_avg_inflow) + 1)

#  Compute 7-Day Rolling Average
rolling_7d_avg = daily_avg_inflow[['se1', 'se2', 'se3', 'se4']].rolling(window=7, center=True).mean()
rolling_7d_avg['day_index'] = daily_avg_inflow['day_index']

# Set up colors per zone
colors = {'se1': 'tab:red', 'se2': 'tab:green', 'se3': 'tab:purple', 'se4': 'tab:orange'}

#  PLOT 1: Hourly Net Import by each zone
# Compute global x-axis limits once
x_min = hourly_net_import['hour_index'].min()
x_max = hourly_net_import['hour_index'].max()

for zone in colors:
    plt.figure(figsize=(16, 6))

    plt.plot(
        hourly_net_import['hour_index'],
        hourly_net_import[zone],
        label=zone.upper(),
        alpha=0.7
    )

    # Axis labels
    plt.xlabel('Hour of Year', fontsize=20)
    plt.ylabel('Net Import (GWh)', fontsize=20)

    # Force identical x-axis for all plots
    plt.xlim(x_min, x_max)

    # Tick styling
    plt.xticks(fontsize=18)
    plt.yticks(fontsize=18)

    # Legend
    plt.legend(
        fontsize=14,
        title="Bidding Zone",
        title_fontsize=14,
        loc="upper right"
    )

    plt.grid(True)
    plt.tight_layout()

    # Save BEFORE show
    plt.savefig(f'hourly_inflow_{zone.upper()}.png', dpi=300)
    plt.show()

"""## Net Transmission"""

#Load excel file
df_net_transmit_2018 = read_dataset('net_transmission_2018.xlsx',path_to_drive)

# Extract relevant data
hourly_net_transmission = df_net_transmit_2018[['hour', 'se1', 'se2', 'se3', 'se4']].copy()
hourly_net_transmission['hour_index'] = range(1, len(hourly_net_transmission) + 1)

# Define list of zones
zones = ['se1', 'se2', 'se3', 'se4']

# Loop to create individual plots for each zone using default colors
for zone in zones:
    plt.figure(figsize=(14, 5))
    plt.plot(hourly_net_transmission['hour_index'], hourly_net_transmission[zone],
             label=zone.upper(), alpha=0.7)  # Default color
    plt.axhline(0, color='white', linewidth=2)
    plt.title(f'Hourly Net Transmission in {zone.upper()} (2018)')
    plt.xlabel('Hour of Year')
    plt.ylabel('Net Import (MW)')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(f'hourly_net_transmission_{zone}.png', dpi=300)
    plt.show()

"""#Output Analysis

## Pareto Frontier Data Load - MinCost
"""

# Load Excel file
#df_pareto3D_cost_min = read_dataset('pareto3D_cost_min.csv',path_to_drive)
df_pareto3D_cost_min = read_dataset('pareto3D_cost_min_2026_01_04.xlsx', path_to_drive)
# Extract coordinates
# Extract coordinates
X = df_pareto3D_cost_min["epsilon_em"]
Y = df_pareto3D_cost_min["epsilon_cvar"]
Z = df_pareto3D_cost_min["cost"]
# Create grids for surface plotting
n = int(np.sqrt(len(df_pareto3D_cost_min)))
X_grid = X.values.reshape(n, n)
Y_grid = Y.values.reshape(n, n)
Z_grid = Z.values.reshape(n, n)

"""## MinCost - Transmission flow"""

#Load excel file
df_cost_min_line_transmit_2018 = read_dataset('cost_min_trans_line_2018.xlsx',path_to_drive)

# Extract relevant data
hourly_net_transmission = df_cost_min_line_transmit_2018[['hour', 'l1', 'l2', 'l3']].copy()
hourly_net_transmission['hour_index'] = range(1, len(hourly_net_transmission) + 1)

# Define a list of transmission lines
lines = ['l1', 'l2', 'l3']

# Loop to create individual plots for each zone using default colors
for line in lines:
    plt.figure(figsize=(14, 5))
    plt.plot(hourly_net_transmission['hour_index'], hourly_net_transmission[line],
             label=line.upper(), alpha=0.7)  # Default color
    plt.axhline(0, color='white', linewidth=2)
    #plt.title(f'Hourly Net Transmission in {line.upper()} (2018)')
    plt.xlabel('Hour of Year')
    plt.ylabel('Net Import (MW)')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(f'hourly_net_transmission_{line}.png', dpi=300)
    plt.show()

"""## Generation Mix for MinCost, MinEmission, MinCVaR"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# -----------------------------
# 1. Raw generation data (MWh)
# -----------------------------
data = [
    # ===== CVaR minimization =====
    ("cvar", "hydro_res", 1.81431e7),
    ("cvar", "hydro_res", 3.6232e7),
    ("cvar", "hydro_ror", 1.85891e6),
    ("cvar", "hydro_res", 9.13532e6),
    ("cvar", "hydro_ror", 460727),
    ("cvar", "hydro_res", 1.0295e6),

    ("cvar", "nuclear", 5.65886e7),
    ("cvar", "chp_waste", 82989.6),
    ("cvar", "chp_gas", 39992.3),
    ("cvar", "chp_biomass", 6.70105e6),

    ("cvar", "wind", 1.54114e6),
    ("cvar", "solar", 1001.85),
    ("cvar", "wind", 4.84808e6),
    ("cvar", "solar", 7089.92),
    ("cvar", "wind", 1.11415e7),
    ("cvar", "solar", 97803.5),
    ("cvar", "wind", 7.4412e6),
    ("cvar", "solar", 41691.7),

    # ===== Emission minimization =====
    ("emission", "hydro_res", 1.81431e7),
    ("emission", "hydro_res", 3.6232e7),
    ("emission", "hydro_ror", 1.85891e6),
    ("emission", "hydro_res", 9.13532e6),
    ("emission", "hydro_ror", 460727),
    ("emission", "hydro_res", 1.0295e6),

    ("emission", "nuclear", 6.81263e7),
    ("emission", "chp_biomass", 3.9635e6),
    ("emission", "chp_biomass", 322725),

    ("emission", "wind", 1.54114e6),
    ("emission", "solar", 1001.85),
    ("emission", "wind", 2.42404e6),
    ("emission", "solar", 7089.92),
    ("emission", "wind", 5.99922e6),
    ("emission", "solar", 97803.5),
    ("emission", "wind", 6.16209e6),
    ("emission", "solar", 41691.7),

    # ===== Cost minimization =====
    ("cost", "hydro_res", 1.81431e7),
    ("cost", "hydro_res", 3.6232e7),
    ("cost", "hydro_ror", 1.85891e6),
    ("cost", "hydro_res", 9.13532e6),
    ("cost", "hydro_ror", 460727),
    ("cost", "hydro_res", 1.0295e6),

    ("cost", "nuclear", 6.72475e+07),
    ("cost", "chp_biomass", 6.95495e+06),
    ("cost", "chp_biomass", 572337),
    ("cost", "chp_waste", 232252),
    ("cost", "chp_gas", 44486),
    ("cost", "chp_peat", 118406),
    ("cost", "oil", 984.195),
    ("cost", "oil", 32719.4),
    ("cost", "gas", 93652.5),

    ("cost", "wind", 1.54114e6),
    ("cost", "solar", 1001.85),
    ("cost", "wind", 2.42404e6),
    ("cost", "solar", 7089.92),
    ("cost", "wind", 5.57077e+06),
    ("cost", "solar", 97803.5),
    ("cost", "wind", 3.7206e+06),
    ("cost", "solar", 41691.7),


]

df = pd.DataFrame(data, columns=["scenario", "technology", "generation"])

# --------------------------------
# 2. Aggregate and normalize (%)
# --------------------------------
grouped = df.groupby(["scenario", "technology"], as_index=False)["generation"].sum()

# Total generation per scenario
totals = grouped.groupby("scenario")["generation"].transform("sum")

# Convert to percentage share
grouped["share_percent"] = 100 * grouped["generation"] / totals

# --------------------------------
# 3. Prepare plot structure
# --------------------------------
tech_order = [
    "hydro_res", "hydro_ror",
    "nuclear", "chp_biomass", "chp_gas", "chp_waste", "chp_peat", "oil", "gas",
    "wind", "solar"
]

scenarios = ["emission", "cvar", "cost"]

plot_data = {
    scenario: grouped[grouped["scenario"] == scenario]
        .set_index("technology")
        .reindex(tech_order)
        .fillna(0)["share_percent"].values
    for scenario in scenarios
}

# --------------------------------
# 4. Plot (Improved Figure 4.15)
# --------------------------------
x = np.arange(len(tech_order))
width = 0.25

colors = {
    "cost": "#08306B",      # dark blue
    "emission": "#4292C6",  # medium blue
    "cvar": "#9ECAE1"       # light blue
}

plt.figure(figsize=(14, 9))

plt.bar(x - width, plot_data["cost"], width,
        label="Cost", color=colors["cost"])
plt.bar(x, plot_data["emission"], width,
        label="Emission", color=colors["emission"])
plt.bar(x + width, plot_data["cvar"], width,
        label="CVaR", color=colors["cvar"])

plt.xticks(x, tech_order, rotation=45, ha="right", fontsize=18)
plt.ylabel("Share of Total Generation (%)", fontsize=18)
plt.xlabel("Technology Type (Grouped by Generation Type)", fontsize=18)

# Y-axis ticks every 5%
y_max = plt.gca().get_ylim()[1]
plt.yticks((np.arange(0, y_max + 1, 10)), fontsize=18)

plt.legend(title="Objective", fontsize=18)
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.tight_layout()
plt.show()

"""## Cost vs Emission at different CVaR levels"""

# Load Excel file
df_pareto3D_cost_min = read_dataset('pareto3D_cost_min_2026_01_04.xlsx',path_to_drive)
# Scale down so that plot can be visible
# Scale conversions
df_pareto3D_cost_min["ε_em_kilo"] = df_pareto3D_cost_min["epsilon_em"] /1e3     # Kilotonne CO₂
df_pareto3D_cost_min["ε_cvar"] = df_pareto3D_cost_min["epsilon_cvar"]         # MWh
df_pareto3D_cost_min["cost_billion"] = df_pareto3D_cost_min["cost"] / 1e9                # Billion SEK

# Plot 1: Cost vs Emission at different CVaR levels
pivot1 = df_pareto3D_cost_min.pivot_table(index="emission", columns="ε_cvar", values="cost_billion")
pivot1.plot(figsize=(10, 6), marker='o', fontsize=16)
# plt.title("Cost vs Emission Cap at Different CVaR Caps (DSR 10%)", fontsize=18)
plt.legend(title="ε_cvar (MW)", fontsize=14, title_fontsize=16)
plt.xlabel("emission (tonnes)", fontsize=18)
plt.ylabel("cost (Billion €)", fontsize=18)
plt.grid(True)
plt.tight_layout()
plt.savefig("Cost_vs_EmissionCap.png")
plt.show()

"""## Cost vs CVaR at different emission levels"""

# Plot 2: Cost vs CVaR at different Emission levels
pivot2 = df_pareto3D_cost_min.pivot_table(index="cvar", columns="ε_em_kilo", values="cost_billion")
pivot2.plot(figsize=(10, 6), marker='o', fontsize=16)
plt.legend(title="ε_emission (kilotonne)", fontsize=14, title_fontsize=16)
#plt.title("Cost vs CVaR Cap at Different Emission Caps (DSR 10%)")
plt.xlabel("CVaR (MW)", fontsize=18)
plt.ylabel("cost (Billion €)", fontsize=18)
plt.grid(True)
plt.tight_layout()
plt.savefig("Cost_vs_CVaRCap.png")
plt.show()

"""## Generation Mix per iteration in MinCost Pareto frontier derivation

*   Role of wind in reducing residual load at high-risk periods
*   As CVaR is relaxed, nuclear generation increases to supply residual demand as a cost-effective and low-emission baseload option
* At CVaR around 8600 - 9200 MW, system relies on existing nuclear, hydro, VRE reducing need for high-emission thermal units

"""

import pandas as pd
import matplotlib.pyplot as plt

# --- 1. Read data ---
# Load dataset
df = read_dataset('gen_mix_iterations.xlsx', path_to_drive)

# --- 2. Clean up column names (optional, in case of slight variations) ---
df.columns = [c.strip().lower() for c in df.columns]

# Ensure scenario is string to avoid mixed-type sorting errors
if 'scenario' in df.columns:
    df['scenario'] = df['scenario'].astype(int)

# Expecting columns like:
# 'scenario', 'node', 'technology', 'generation (mwh)', 'rate', 'emission', 'generation(mw)'
# Rename to simpler names
rename_map = {
    'generation (mwh)': 'gen_mwh',
    'generation(mw)': 'gen_mw'
}
df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})

# --- 3. Aggregate per scenario & technology ---
agg = (
    df.groupby(['scenario', 'technology'], as_index=False)
      .agg(
          emission_sum=('emission', 'sum'),
          gen_mw_sum=('gen_mw', 'sum')
      )
)

# --- 4. Sort by scenario for nice plotting ---
agg = agg.sort_values(['technology', 'scenario'])

#-----------------------

# --- 3. Keep only technologies with total emission > 0 over all scenarios ---
tech_with_emission = (
    agg.groupby("technology")["emission_sum"]
       .sum()
       .loc[lambda s: s > 0]
       .index
)

agg_nonzero = agg[agg["technology"].isin(tech_with_emission)]

# --- 4. Pivot to wide format for stacked bars ---
pivot = agg_nonzero.pivot(
    index="scenario",
    columns="technology",
    values="emission_sum"
).fillna(0)

pivot = pivot.sort_index()

# --- 5. Stacked bar chart (only emitting technologies appear & thus in legend) ---
plt.figure(figsize=(12, 6))

bottom = None
for tech in pivot.columns:
    if bottom is None:
        plt.bar(pivot.index, pivot[tech], label=tech)
        bottom = pivot[tech].copy()
    else:
        plt.bar(pivot.index, pivot[tech], bottom=bottom, label=tech)
        bottom += pivot[tech]

plt.xlabel("Iteration", fontsize=18)
plt.ylabel("Emission (tonnes)", fontsize=18)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
#plt.title("Stacked emissions by emitting generation technologies over iterations")
plt.legend(title="Technology", bbox_to_anchor=(1.05, 1), loc="upper left", fontsize=14, title_fontsize=16)
plt.tight_layout()
plt.show()


# --- 6. Get list of technologies and scenarios ---
technologies = agg['technology'].unique()
scenarios = sorted(agg['scenario'].unique())

#----8. Plot in another way

plt.figure(figsize=(10, 6))

# Define styles by technology group
line_styles = {}
colors = {}

for tech in technologies:
    if tech in ["res", "hydro"]:   # hydro / reservoir group
        colors[tech] = "blue"
        line_styles[tech] = "--"   # e.g. dashed
    elif tech == "ror":            # run-of-river
        colors[tech] = "green"
        line_styles[tech] = "--"   # same pattern as res
    elif tech in ["wind", "solar"]:  # VRE
        line_styles[tech] = "-."   # common VRE pattern
        if tech == "wind":
            colors[tech] = "purple"
        else:                      # solar
            colors[tech] = "orange"
    elif tech == "nuclear":
        colors[tech] = "brown"
        line_styles[tech] = ":"    # dotted, unique for nuclear
    else:
        # emitting thermal / CHP units: gas, oil, chp_*, etc.
        line_styles[tech] = "-"    # same solid pattern
        # let matplotlib cycle colours, or set manually if you prefer:
        # e.g. a specific mapping
        default_color_map = {
            "gas": "tab:blue",
            "oil": "tab:pink",
            "chp_gas": "tab:orange",
            "chp_peat": "tab:green",
            "chp_waste": "tab:red",
            "chp_coal": "tab:gray",
            "chp_biomass": "tab:olive"
        }
        colors[tech] = default_color_map.get(tech, None)  # None => auto

# Plot with custom style
for tech in technologies:
    sub = agg[agg["technology"] == tech].sort_values("scenario")
    plt.plot(
        sub["scenario"],
        sub["gen_mw_sum"],
        marker="o",
        linestyle=line_styles.get(tech, "-"),
        color=colors.get(tech, None),
        label=tech
    )

plt.xlabel("Iteration", fontsize=18)
plt.ylabel("Generation (MW)", fontsize=18)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
#plt.title("Generation (MW) over iterations by generation technology")
plt.legend(title="Technology", bbox_to_anchor=(1.05, 1), loc="upper left", fontsize=14, title_fontsize=16)
plt.grid(True)
plt.tight_layout()
plt.show()

"""## Pareto Frontier - DSR 10% without the line trace for a particular emission"""

# Extract values
eps_em_vals = sorted(df_pareto3D_cost_min["emission"].unique())
eps_q_vals = sorted(df_pareto3D_cost_min["cvar"].unique())


# Pivot the data into grids for surface plot
Z_cost = df_pareto3D_cost_min.pivot(index="epsilon_cvar", columns="epsilon_em", values="cost").values
Z_emission = df_pareto3D_cost_min.pivot(index="epsilon_cvar", columns="epsilon_em", values="emission").values
Z_cvar = df_pareto3D_cost_min.pivot(index="epsilon_cvar", columns="epsilon_em", values="cvar").values

# Create meshgrid
X, Y = np.meshgrid(eps_em_vals, eps_q_vals)

# Create surface plot
fig = go.Figure(data=[go.Surface(
    z=Z_cost,
    x=X,
    y=Y,
    colorscale='Viridis',
    opacity=0.9,
    showscale=True,
    colorbar=dict(title='Cost')  # Ensure color legend appears
)])

# Layout
fig.update_layout(
    scene=dict(
        xaxis=dict(title=dict(text='Emission (in tonnes)', font=dict(size=18)), tickfont=dict(size=14)),
        yaxis=dict(title=dict(text='CVaR (in MW))', font=dict(size=18)), tickfont=dict(size=14)),
        zaxis=dict(title=dict(text='cost (in €)', font=dict(size=18)), tickfont=dict(size=14)),
        camera=dict(eye=dict(x=1.4, y=1.4, z=1.2))
        ),
    width=1000,
    height=800,
    margin=dict(l=20, r=20, b=20, t=40)  # reduced top margin
)
fig.show()
#fig.write_image("Pareto_Surface_cost_min.png", scale=2)

"""## Pareto Frontier - DSR 10% with the line trace for particular emission levels"""

import plotly.graph_objects as go
import pandas as pd
import numpy as np

# Read pareto 3D cost minimization
df_pareto20_cost_min = read_dataset('pareto3D_cost_min_2026_01_04.xlsx', path_to_drive)

# Extract values for surface
eps_em_vals = sorted(df_pareto20_cost_min["emission"].unique())
eps_q_vals = sorted(df_pareto20_cost_min["cvar"].unique())
Z_cost = df_pareto20_cost_min.pivot(
    index="epsilon_cvar",
    columns="epsilon_em",
    values="cost"
).values

X, Y = np.meshgrid(eps_em_vals, eps_q_vals)

# Create the base surface plot
fig = go.Figure(data=[go.Surface(
    z=Z_cost, x=X, y=Y,
    colorscale='Viridis',
    opacity=0.8,
    showscale=True,
    colorbar=dict(
        title='Cost (€)',
        titlefont=dict(size=20),
        tickfont=dict(size=20),
        len=0.7
    )
)])

# Load the dataset for the line trace from the specified file
df_line_trace = read_dataset('trace_line_graph_on_pareto.xlsx', path_to_drive)
df_line_trace1 = read_dataset('trace_line_graph_on_pareto1.xlsx', path_to_drive)

# Build tuple labels
tuple_labels = []
for e, cvar, cost in zip(
    df_line_trace["emission"],
    df_line_trace["cvar"],
    df_line_trace["cost"]
):
    e_k    = e / 1000.0     # if you later want to use emission too
    cvar_k = cvar / 1000.0
    cost_b = cost / 1e9

    label = f"({e_k:.2f}k,{cvar_k:.2f}k, {cost_b:.2f}B)"
    tuple_labels.append(label)

tuple_labels1 = []
for e1, cvar1, cost1 in zip(
    df_line_trace1["emission"],
    df_line_trace1["cvar"],
    df_line_trace1["cost"]
):
    e1_k    = e1 / 1000.0     # if you later want to use emission too
    cvar1_k = cvar1 / 1000.0
    cost1_b = cost1 / 1e9

    label1 = f"({e1_k:.2f}k,{cvar1_k:.2f}k, {cost1_b:.2f}B)"
    tuple_labels1.append(label1)

# Pareto 3D layout
fig.update_layout(
    scene=dict(
        xaxis=dict(
            title=dict(
                text="Emission (tonnes)",
                font=dict(size=20)
            ),
            tickfont=dict(size=16)
        ),
        yaxis=dict(
            title="CVaR (MW)",
            titlefont=dict(size=20),
            tickfont=dict(size=16)
        ),
        zaxis=dict(
            title="Cost (€)",
            titlefont=dict(size=20),
            tickfont=dict(size=16)
        ),
        camera=dict(eye=dict(x=1.6, y=1.2, z=1.4))
    ),
    width=1800, height=1400,
    margin=dict(l=50, r=50, b=50, t=80)
)

# Add the line trace connecting the points (no text here)
fig.add_trace(go.Scatter3d(
    x=df_line_trace["emission"],  # realized values
    y=df_line_trace["cvar"],      # realized values
    z=df_line_trace["cost"],      # realized values
    mode='lines+markers',
    marker=dict(size=7, color='blue'),
    line=dict(color='blue', width=3),
    name="Line Trace"
))

fig.add_trace(go.Scatter3d(
    x=df_line_trace1["emission"],  # realized values
    y=df_line_trace1["cvar"],      # realized values
    z=df_line_trace1["cost"],      # realized values
    mode='lines+markers',
    marker=dict(size=7, color='blue'),
    line=dict(color='blue', width=3),
    name="Line Trace"
))

# --- Add 3D annotations with white background for the tuples ---
annotations = []

# First dataset annotations
z_offset = 0.01 * df_line_trace["cost"].max()
for e, cvar, cost, label in zip(
    df_line_trace["emission"],
    df_line_trace["cvar"],
    df_line_trace["cost"],
    tuple_labels
):
    annotations.append(dict(
        showarrow=False,
        x=e,
        y=cvar,
        z=cost + z_offset,
        text=label,
        xanchor="center",
        font=dict(color="black", size=16),
        bgcolor="white",
        bordercolor="black",
        borderwidth=1
    ))

# Second dataset annotations
z_offset1 = 0.01 * df_line_trace1["cost"].max()
for e1, cvar1, cost1, label1 in zip(
    df_line_trace1["emission"],
    df_line_trace1["cvar"],
    df_line_trace1["cost"],
    tuple_labels1
):
    annotations.append(dict(
        showarrow=False,
        x=e1,
        y=cvar1,
        z=cost1 + z_offset1,
        text=label1,
        xanchor="center",
        font=dict(color="black", size=16),
        bgcolor="white",
        bordercolor="black",
        borderwidth=1
    ))


fig.update_layout(
    scene=dict(
        **fig.layout.scene.to_plotly_json(),  # keep existing scene settings
        annotations=annotations
    )
)

fig.show()

"""## Pareto Frontier - DSR 20% with the line trace for particular emission levels"""

import plotly.graph_objects as go
import pandas as pd
import numpy as np

# Read pareto 3D cost minimization
df_pareto20_cost_min = read_dataset('pareto_dsr20.xlsx', path_to_drive)

# Extract values for surface
eps_em_vals = sorted(df_pareto20_cost_min["emission"].unique())
eps_q_vals = sorted(df_pareto20_cost_min["cvar"].unique())
Z_cost = df_pareto20_cost_min.pivot(
    index="epsilon_cvar",
    columns="epsilon_em",
    values="cost"
).values

X, Y = np.meshgrid(eps_em_vals, eps_q_vals)

# Create the base surface plot
fig = go.Figure(data=[go.Surface(
    z=Z_cost, x=X, y=Y,
    colorscale='Viridis',
    opacity=0.8,
    showscale=True,
    colorbar=dict(
        title='Cost (€)',
        titlefont=dict(size=20),
        tickfont=dict(size=20),
        len=0.7
    )
)])

# Load the dataset for the line trace from the specified file
df_line_trace = read_dataset('trace_line_graph_on_pareto_20.xlsx', path_to_drive)
df_line_trace1 = read_dataset('trace_line_graph_on_pareto_20_1.xlsx', path_to_drive)

# Build tuple labels
tuple_labels = []
for e, cvar, cost in zip(
    df_line_trace["emission"],
    df_line_trace["cvar"],
    df_line_trace["cost"]
):
    e_k    = e / 1000.0     # if you later want to use emission too
    cvar_k = cvar / 1000.0
    cost_b = cost / 1e9

    label = f"({e_k:.2f}k,{cvar_k:.2f}k, {cost_b:.2f}B)"
    tuple_labels.append(label)

tuple_labels1 = []
for e1, cvar1, cost1 in zip(
    df_line_trace1["emission"],
    df_line_trace1["cvar"],
    df_line_trace1["cost"]
):
    e1_k    = e1 / 1000.0     # if you later want to use emission too
    cvar1_k = cvar1 / 1000.0
    cost1_b = cost1 / 1e9

    label1 = f"({e1_k:.2f}k,{cvar1_k:.2f}k, {cost1_b:.2f}B)"
    tuple_labels1.append(label1)

# Pareto 3D layout
fig.update_layout(
    scene=dict(
        xaxis=dict(
            title=dict(
                text="Emission (tonnes)",
                font=dict(size=20)
            ),
            tickfont=dict(size=16)
        ),
        yaxis=dict(
            title="CVaR (MW)",
            titlefont=dict(size=20),
            tickfont=dict(size=16)
        ),
        zaxis=dict(
            title="Cost (€)",
            titlefont=dict(size=20),
            tickfont=dict(size=16)
        ),
        camera=dict(eye=dict(x=1.6, y=1.2, z=1.4))
    ),
    width=1800, height=1400,
    margin=dict(l=50, r=50, b=50, t=80)
)

# Add the line trace connecting the points (no text here)
fig.add_trace(go.Scatter3d(
    x=df_line_trace["emission"],  # realized values
    y=df_line_trace["cvar"],      # realized values
    z=df_line_trace["cost"],      # realized values
    mode='lines+markers',
    marker=dict(size=7, color='blue'),
    line=dict(color='blue', width=3),
    name="Line Trace"
))

fig.add_trace(go.Scatter3d(
    x=df_line_trace1["emission"],  # realized values
    y=df_line_trace1["cvar"],      # realized values
    z=df_line_trace1["cost"],      # realized values
    mode='lines+markers',
    marker=dict(size=7, color='blue'),
    line=dict(color='blue', width=3),
    name="Line Trace"
))

# --- Add 3D annotations with white background for the tuples ---
annotations = []

# First dataset annotations
z_offset = 0.01 * df_line_trace["cost"].max()
for e, cvar, cost, label in zip(
    df_line_trace["emission"],
    df_line_trace["cvar"],
    df_line_trace["cost"],
    tuple_labels
):
    annotations.append(dict(
        showarrow=False,
        x=e,
        y=cvar,
        z=cost + z_offset,
        text=label,
        xanchor="center",
        font=dict(color="black", size=16),
        bgcolor="white",
        bordercolor="black",
        borderwidth=1
    ))

# Second dataset annotations
z_offset1 = 0.01 * df_line_trace1["cost"].max()
for e1, cvar1, cost1, label1 in zip(
    df_line_trace1["emission"],
    df_line_trace1["cvar"],
    df_line_trace1["cost"],
    tuple_labels1
):
    annotations.append(dict(
        showarrow=False,
        x=e1,
        y=cvar1,
        z=cost1 + z_offset1,
        text=label1,
        xanchor="center",
        font=dict(color="black", size=16),
        bgcolor="white",
        bordercolor="black",
        borderwidth=1
    ))


fig.update_layout(
    scene=dict(
        **fig.layout.scene.to_plotly_json(),  # keep existing scene settings
        annotations=annotations
    )
)

fig.show()

"""## DSR 10% vs. DSR 20% analysis

* Limited system benefit
* DSR does not drive the system cost but CVaR does
* Invest in other flexible measures like storage or grid expansion instead of more DSR
"""

import pandas as pd
import matplotlib.pyplot as plt

# --- 1. Read data ---
# Load dataset
df = read_dataset('dasr10-vs-20-portfolio.xlsx', path_to_drive)
df.columns = [c.strip().lower() for c in df.columns]

# Expect columns: cost_20, emission_20, cvar_20, cost_10, emission_10, cvar_10
# Keep only numeric rows (drop trailing text rows if present)
numeric_cols = ["cost_20", "cvar_20", "cost_10", "cvar_10"]
df = df[pd.to_numeric(df["cost_20"], errors="coerce").notna()].copy()
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

# --- 2. Sort by CVaR for nicer lines ---
df_20 = df.sort_values("cvar_20")
df_10 = df.sort_values("cvar_10")

# --- 3. Single plot with both DSR levels ---
plt.figure(figsize=(8, 5))

plt.plot(df_10["cvar_10"], df_10["cost_10"] / 1e9,
         marker="o", linestyle="-", color="tab:blue", label="DSR 10%")
plt.plot(df_20["cvar_20"], df_20["cost_20"] / 1e9,
         marker="s", linestyle="--", color="tab:orange", label="DSR 20%")

plt.xlabel("CVaR (MW)", fontsize=18)
plt.ylabel("Cost (billion €)", fontsize=18)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
#plt.title("Cost vs CVaR for DSR 10% and DSR 20%")
plt.legend(fontsize=18)
plt.grid(True)
plt.tight_layout()
plt.show()


#-------------cost vs emission-------

# Keep numeric rows and convert
numeric_cols = ["cost_20", "emission_20", "cost_10", "emission_10"]
df = df[pd.to_numeric(df["cost_20"], errors="coerce").notna()].copy()
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

df_20 = df.sort_values("emission_20")
df_10 = df.sort_values("emission_10")

# Emission vs Cost (cost on Y-axis)
plt.figure(figsize=(8, 5))
plt.plot(df_10["emission_10"] / 1e3, df_10["cost_10"] / 1e9,
         marker="o", linestyle="-", color="tab:blue", label="DSR 10%")
plt.plot(df_20["emission_20"] / 1e3, df_20["cost_20"] / 1e9,
         marker="s", linestyle="--", color="tab:orange", label="DSR 20%")

plt.xlabel("Emission (kilotonne)", fontsize=18)
plt.ylabel("Cost (billion €)", fontsize=18)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
#plt.title("Cost vs Emission for DSR 10% and 20%")
plt.legend(fontsize=18)
plt.grid(True)
plt.tight_layout()
plt.show()